# Generated by Django 3.1.1 on 2020-09-18 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_drf', '0002_voucher_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='description',
        ),
    ]
