# Generated by Django 3.1.1 on 2020-09-18 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_drf', '0004_voucher_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
