# Generated by Django 3.1.1 on 2020-09-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_drf', '0006_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='discount',
            field=models.CharField(default='0% OFF', max_length=15),
        ),
    ]
