# Generated by Django 3.1.1 on 2020-09-19 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_drf', '0008_voucher_no_of_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
